---
- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"

- name: Home Assistant Docker Container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    pull: true
    volumes:
      - "{{ homeassistant_data_directory }}/config:/config:rw"
    network_mode: host
    restart_policy: unless-stopped
    env:
      TZ: "{{ ansible_nas_timezone }}"
    devices:
      - "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_04248c792e1aec1188587fe5f01c6278-if00-port0:/dev/ttyUSB0:rwm"
    labels:
      traefik.enable: "{{ homeassistant_available_externally | string }}"
      traefik.http.routers.homeassistant.rule: "Host(`{{ homeassistant_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.homeassistant.tls.certresolver: "letsencrypt"
      traefik.http.routers.homeassistant.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.homeassistant.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
    memory: "{{ homeassistant_memory }}"
